version: '3.9'

services:
  # Backend API service
  backend:
    build: 
      context: ./ai-notes-summarizer
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./ai-notes-summarizer/.env
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:yourpassword@db:5432/ai_notes_db}
    depends_on:
      - db
    networks:
      - app-network

  # Frontend React/Vite service
  frontend:
    build:
      context: ./ai-notes-summarizer-fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network

  # PostgreSQL database service
  db:
    image: postgres:15
    restart: always
    env_file:
      - ./ai-notes-summarizer/.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-yourpassword}
      - POSTGRES_DB=${POSTGRES_DB:-ai_notes_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
