version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./src:/app/src
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/notes_db
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: